package br.upe.sicc.entidade;

public enum EnumEscolaridade {
	
		FUNADEMENTAL_INCOMPLETO,
		FUNDAMENTAL_COMPLETO,
		MEDIO_INCOMPLETO,
		MEDIO_COMPLETO,
		SUPERIOR_INCOMPLETO,
		SUPERIOR_COMPLETO, 
		POS_GRADUACAO_INCOMPLETO,
		POS_GRADUACAO_COMPLETO;
		
}
